grpc_url = "http://cosmos-grpc.polkachu.com"
grpc_port = "14990"
chain_id = "cosmoshub-4"
chain_denom = "uatom"
deposit_denom = "ibc/6F8F0E9D472BF053261F2DEBE521801B703372777F3923B48DAE55D4F1212B5F"
ica_address = "cosmos1zhetc0qx9rfumdw6stekdyg4l557z9lz6hk9w7h072xeusm3z24qxs38tu"
