grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
supervault = "neutron1tamvnzeq9e4w6leav38htqutz4ht8jhm8ujp6s3sfsg9yu69kqeq7ygf9a"
authorizations = "neutron1fx7gpeed0h3y9w983kty7jp84qx4lqlmh0pzcz7aywg7nr59g7vqjl2hsn"
processor = "neutron1u5peg6zd87sjg5frfrst4s696t7dwcdml4pmenxelqvc32gfvmus673fvj"

[denoms]
deposit_token = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn = "untrn"
supervault_lp = "factory/neutron1tamvnzeq9e4w6leav38htqutz4ht8jhm8ujp6s3sfsg9yu69kqeq7ygf9a/BTC-USDC"

[accounts]
deposit = "neutron1npx5g6ksgu6hxp7q7a0e5r4te05d5hn7ldd6adr8mfn39z9jhnaslcelsu"
settlement = "neutron1wvlwsa3hl3zcu9ks23gnnn7u3fl9jtmz7wadckgz32ssnym6m2xspkercf"

[libraries]
supervault_lper = "neutron1gj4h2rv3mysngj6kzwhyn5yvc5tvmpv7tlq8j9cavg2cfz8mdu3qqaac7l"
clearing_queue = "neutron14fla37g806ty3jz3tmmfgutee0we3tcvcs5zhd8axppvpev6gvrseu42yv"

[coprocessor_app_ids]
clearing_queue = "919c2d9063536ac2060239612eb52d6d5b8ab86b6f053c19402efee318e6faf1"
