[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Neutron multisig address

[vault]
deposit_token            = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
strategist               = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Address of the strategist
platform_fee_account     = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the platform fees portion
strategist_fee_account   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 0                                            # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "10000000000"                                # scaling factor for rate updates
deposit_cap              = "50000000000"                                # 500 BTC
deposit_fee_bps          = 2                                            # 0.025% deposit fee
withdraw_fee_bps         = 2                                            # 0.025% withdraw fee
max_rate_increment_bps   = 100                                          # 20% maximum rate increment per update
max_rate_decrement_bps   = 100                                          # 20% maximum rate decrement per update
starting_rate            = "100000000"                                  # 1e8 - WBTC Precision - 8 decimals
min_rate_update_delay    = 14400                                        # 4 hours - Minimum delay for rate updates
max_rate_update_delay    = 129600                                       # 36 hours in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "cosmos1frq8px66kplgp23fxzgpzeg3xf802nt72r2svjsnnq0x0zav72yq58vy5x"
source_client              = "cosmoshub-0"
timeout                    = 43200                                                               # 12 hours in seconds
ibc_transfer_threshold_amt = 8928571

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "340245338d1b4987580f557935fb8e11e7a998f734603b57eef269b1b08b0b47" # TBD after we have the app deployed
