[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Neutron multisig address

[wrapper]
zk_me                    = "0x3919BdCe285E82CDC6585979cfd71636b33A5582" # Should be updated to correct ZkMe Verify & Certify contract address
cooperator               = "0x3f4b2F33e5488796cBA66C6b1E9f1934031656Fd" # Should be updated to correct cooperator provided from ZkMe

[vault]
deposit_token            = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599" # Should be updated to correct deposit token address (e.g. WBTC)
strategist               = "0x0EDF77a1036598Da1C0Aab471066a0c4FFd099D1" # Address of the strategist
platform_fee_account     = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Receiver of the platform fees portion
strategist_fee_account   = "0x0EDF77a1036598Da1C0Aab471066a0c4FFd099D1" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 0                                            # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "10000000000"                                # scaling factor for rate updates
deposit_cap              = "50000000000"                                # 500 BTC
deposit_fee_bps          = 3                                            # 0.03% deposit fee
withdraw_fee_bps         = 2                                            # 0.02% withdraw fee
max_rate_increment_bps   = 200                                          # 20% maximum rate increment per update
max_rate_decrement_bps   = 200                                          # 20% maximum rate decrement per update
starting_rate            = "100000000"                                  # 1e8 - WBTC Precision - 8 decimals
min_rate_update_delay    = 14400                                        # 4 hours - Minimum delay for rate updates
max_rate_update_delay    = 129600                                       # 36 hours in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "cosmos1uscvz98t3ce7hp4ch8qtg0zkdpafr9qvkcaalcxfe24k028ws33stj5lt7" # Eventual ICA address
source_client              = "cosmoshub-0"
timeout                    = 43200                                        # 12 hours in seconds
ibc_transfer_threshold_amt = 10000000

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "" # TBD after deployment
