grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
maxbtc_contract = "neutron17sp75wng9vl2hu3sf4ky86d7smmk3wle9gkts2gmedn9x4ut3xcqa5xp34"
supervault_contract = "neutron1r8qcd94anqhrfzmjyppk45pew5kzedrxz8mgk82kmwadqyndvwtstp9yrn"
authorizations = "neutron15uhy20x9u7v07enttt8qcrl9lfj7u7rdft5c4jnd43uhxuj74nls5wn34p"
processor = "neutron1f2g8q7q8h3dahqlafp64d0wqaep7yka02fs0ztpl0cjucp77smkqftq7jp"

[denoms]
deposit_token = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"
ntrn = "untrn"
maxbtc = "factory/neutron17sp75wng9vl2hu3sf4ky86d7smmk3wle9gkts2gmedn9x4ut3xcqa5xp34/maxbtc"
supervault_lp = "factory/neutron1r8qcd94anqhrfzmjyppk45pew5kzedrxz8mgk82kmwadqyndvwtstp9yrn/BTC-BTC"

[accounts]
gaia_ica = "neutron1x86kjy9vparftx2nw22p2z4msylssj3pm9jgwfy4m2fxmdklf0csa7qpwg"
ica_deposit = "neutron18y4a7ujfx7eq620w78cl0mdrpl323tuq63t26eg7357w096nypnsrah47v"
supervault_deposit = "neutron1tgd6zx9qggham0nzd40fvesfwhwy8hj9mht68xn4jn7uzvdslv3qa3qwmt"
settlement = "neutron19nj0ppy8hgvdydp8vyks8cczutlm7hjcpcaryx7ux277ew7kpn6q2t9yhj"

[libraries]
maxbtc_issuer = "neutron1p0m0fs7psf0ts5yyucf4j04tyj8qs94zh87dxa357zcfjgwlefaqc93cl6"
clearing_queue = "neutron1qzxuxfmfjzjqvkeu3tlftsw8ywxj57zvakdnwjw9t7ra5h4tky4qe5hflv"
ica_transfer_gaia = "neutron17f2jk76ue49nesua9xz4hfvcj06lkk784934np9xn4vzsgkr2krqvq8yl8"
supervault_lper = "neutron1hyn2kghgtuwp6a8f8jlevywdv8ydezy3nef2c3s7getrhtq48arqclh89d"

[coprocessor_app_ids]
clearing_queue = "8df0ca532a93a899bd22018578784050a2923e8bbf5cf82a96620a3a710b2a05"
