[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Neutron multisig address

[vault]
deposit_token            = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" # USDC on Ethereum
strategist               = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Address of the strategist
platform_fee_account     = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the platform fees portion
strategist_fee_account   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 0                                            # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "1000000000000"                              # scaling factor for rate updates
deposit_cap              = "3000000000000"                              # e.g. 3_000_000 USDC
deposit_fee_bps          = 2                                            # 0.02% deposit fee
withdraw_fee_bps         = 2                                            # 0.02% withdraw fee
max_rate_increment_bps   = 2000                                         # 20% maximum rate increment per update
max_rate_decrement_bps   = 2000                                         # 20% maximum rate decrement per update
starting_rate            = "1000000"                                    # 1e6 - USDC Precision - 6 decimals
min_rate_update_delay    = 14400                                        # 4 hours - Minimum delay for rate updates
max_rate_update_delay    = 129600                                       # 36 hours in seconds - Maximum delay for rate updates before vault gets paused

[cctp_transfer]
cctp_token_messenger        = "0xBd3fa81B58Ba92a82136038B25aDec7066af3155"                         # CCTP Token Messenger contract address
recipient                   = "0x000000000000000000000000CE1E2FE19786376A19323615C364A0A24B616139" # Forwarding Account on Noble
destination_domain          = 4                                                                    # Noble
cctp_transfer_threshold_amt = 10
