grpc_url = "grpc_url"
grpc_port = "grpc_port"
chain_id = "chain_id"
chain_denom = "uatom"
deposit_denom = "ibc/D742E8566B0B8CC8F569D950051C09CF57988A88F0E45574BFB3079D41DE6462"
ica_address = "cosmos1cfrnnl9a4sxwhleler8q64v8z8zfgduan98fn0s4spe7eu4felnsnydamw"
