grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1et4xza4pge3asumk8yxdx6qm85k9eplk0kathtkheln6znxsqheqfytsza"
authorizations = "neutron18ts9jpk9twh2fa52dmag6c4g4dac4se7kfxgjpgfnzp339t9at5szmz9ah"
processor = "neutron10vssuhu5rv8wyhzwt3296xfem6tzwh7q7275a5d0pv8ppm8jm29svfer3f"

[denoms]
deposit_token = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"
ntrn = "untrn"

[accounts]
ica = "neutron1ujm20sffk4j4w39flnv2qpth5v3yccvfgq4w8lgg88mqktvx0hdsr5j5at"
deposit = "neutron1rc3uuyqgdvdlv5h5fxgt443sjnhcv4ptp7v8qgagp72cjyex55lqm2g5fm"
settlement = "neutron1dd8pvy3hqaq0xmlwchgvc6cmnfrxe5nd8weqh7jpejtt7mhg3vasq4d984"

[libraries]
mars_lending = "neutron1w4dvesr0t30d8gqt0u5zz5h8lnyhu0tx4cpuw53gzxnce4w26j4q6yw5z8"
clearing_queue = "neutron1y2t9s6t6gdgks99y2lzldehawmld5kx0w7lscsw0gkymywwz5szste9m5j"
ica_transfer = "neutron1ua9yxkx5fustxj25sjnn78gz6ys0vykguhk2ftn8x9fuu2qdm3mqepuvfw"

[coprocessor_app_ids]
clearing_queue = "df008c9e5875a49416639b3fbe9845c657f893c60049184c606bb55d1e961092"
