[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Neutron multisig address

[vault]
deposit_token            = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599" # WBTC
strategist               = "0x62d8bfc7050AbaE89397c9F1602e132D1Fd81Dd8" # Address of the strategist
platform_fee_account     = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Receiver of the platform fees portion
strategist_fee_account   = "0x62d8bfc7050AbaE89397c9F1602e132D1Fd81Dd8" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 0                                            # Strategist fee is 0%, rest goes to the platform (50%)
scaling_factor           = "10000000000"                                # scaling factor for rate updates
deposit_cap              = "5000000000"                                 # 50 BTC
deposit_fee_bps          = 3                                            # 0.03% deposit fee
withdraw_fee_bps         = 2                                            # 0.02% withdraw fee
max_rate_increment_bps   = 200                                          # 2% maximum rate increment per update
max_rate_decrement_bps   = 200                                          # 2% maximum rate decrement per update
starting_rate            = "100000000"                                  # 1e8 - bitcoin LST precision - 8 decimals
min_rate_update_delay    = 14400                                        # 14 hours - Minimum delay for rate updates - for testing purposes
max_rate_update_delay    = 129600                                       # 36 hours in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "cosmos1gz408esrqkg2q6fecc3v0522dzccgzhx5xjrdsc6ykj6aga8jkkqyyjkhg" # Eventual ICA address
source_client              = "cosmoshub-0"
timeout                    = 43200                                       # 12 hours in seconds
ibc_transfer_threshold_amt = 1080000000                                  # $10000 in BTC

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "e0e292b06e885d2dc86da51256b1f462447b41b6b23d7a8dc70ddcbaa712ff83" # TBD after deployment
